# Generated by Django 4.2.7 on 2023-11-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_position', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffposition',
            options={'verbose_name': 'Позиция сотрудника', 'verbose_name_plural': 'Позиции сотрудников'},
        ),
    ]
