# Generated by Django 4.2.7 on 2023-11-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrideStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128, verbose_name='ФИО')),
                ('graduation_year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('description', models.TextField(verbose_name='Информация об ученике')),
                ('photo', models.ImageField(upload_to='pride_students_photos', verbose_name='Фото')),
                ('current_position', models.CharField(max_length=128, verbose_name='Текущяя позиция')),
            ],
            options={
                'verbose_name': 'Гордость школы',
                'verbose_name_plural': 'Гордости школы',
            },
        ),
    ]
