# Generated by Django 4.2.7 on 2023-11-24 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_position', '0002_alter_staffposition_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='О сотруднике')),
                ('photo', models.ImageField(upload_to='staff_photos', verbose_name='Фото сотрудника')),
                ('experience', models.PositiveIntegerField(verbose_name='Стаж сотрудника (в годах)')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_position.staffposition', verbose_name='Позиция сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
